---
title: "lab10.rmd"
author: "Shawn Vizgan"
date: "5/12/2021"
output: html_document
---
1) 
```{r}

Subject <- c(rep(c("s1","s2","s3","s4","s5"),2),
             rep(c("s6","s7","s8","s9","s10"),2))
Phonological_Similarity <- rep(rep(c("b1","b2"), each=5),2)
Age <- rep(c("a1","a2"), each=10)
num_correct <- c(15,23,12,16,14,
                 13,19,10,16,12,
                 39,31,40,32,38,
                 29,15,30,26,30)
bat_hat_data <- tibble(Subject,
                       Phonological_Similarity,
                       Age,
                       num_correct)

aov_out <- aov( num_correct ~ Phonological_Similarity*Age + Error(Subject/Phonological_Similarity), data = bat_hat_data)
summary(aov_out)
```

2)
```{r}
# get the data into R in long format
subject <- rep(c("s1","s2","s3","s4"), each=10)
Typicality_B <- rep(rep(c("b1","b2"), each=5),4)
Faces_A <- rep(c("a1","a2","a3","a4","a5"),8)
#Faces_A <- rep(c("a1","a2","a3","a4","a5",
#                 "a6","a7","a8","a9","a10"),4)
centiseconds <- c(20,22,25,24,19,37,37,43,48,45,
                   9,8,21,21,21,34,35,35,37,39,
                   18,20,18,21,33,35,39,39,37,40,
                   5,14,16,22,23,38,49,51,50,52)
face_data <-  tibble(subject,
                     Typicality_B,
                     Faces_A,
                     centiseconds)
# run the anova
aov_out <- aov(centiseconds  ~ (subject + 
                                Faces_A%in%Typicality_B + 
                                Typicality_B + 
                                Typicality_B:subject),
               data = face_data)
summary(aov_out)
```

