---
title: "lab4.rmd"
author: "Shawn Vizgan"
date: "4/11/2021"
output: html_document
---

```{r}
library(tibble)
example_data <- tibble(Group = rep(c("A","B"), each = 5),
                       DV = c(2,4,3,5,4,7,6,5,6,7))
```
1.

```{r}
my_t <- t.test(DV~Group, var.equal=TRUE, data = example_data)
my_aov <- summary(aov(DV~Group, data = example_data))
my_t$p.value
my_aov[[1]]$`Pr(>F)`[1]
round(my_t$p.value, digits=5) == round(my_aov[[1]]$`Pr(>F)`[1], digits =5)
my_t$statistic^2
my_aov[[1]]$`F value`[1]
round(my_t$statistic^2, digits=1) == round(my_aov[[1]]$`F value`[1], digits=1)
```

2.
```{r}
library(data.table)
all_data <- fread("data/Jamesetal2015Experiment2.csv")
# re-labelling
all_data$Condition <- as.factor(all_data$Condition)
levels(all_data$Condition) <- c("Control",
                                "Reactivation+Tetris", 
                                "Tetris_only",
                                "Reactivation_only")
library(ggplot2)
ggplot(all_data, aes(x=Condition, y=Days_One_to_Seven_Number_of_Intrusions))+
  geom_bar(stat="summary", fun= "mean", position="dodge")+
  geom_point()
my_aov <- aov(Days_One_to_Seven_Number_of_Intrusions~Condition, data = all_data)
summary(my_aov)
library(papaja)
#apa_print(my_aov)$full_result$Condition
```



