---
title: "lab5.rmd"
author: "Shawn Vizgan"
date: "5/12/2021"
output: html_document
---



1)
```{r}
library(tibble)
levels <- 3
n_per_level <- 10
critical_F <- qf(.95,2,27)
# repeat until we find the data that meets the criterion
for(i in 1:1000){
  random_data <- tibble(subjects = 1:(levels*n_per_level),
                        IV = as.factor(rep(1:levels, each = n_per_level)),
                        DV = rnorm(levels*n_per_level, 0, 1)
                        )
  aov.out <- aov(DV ~ IV, data = random_data)
  simulated_F <- summary(aov.out)[[1]]$`F value`[1]
  
  if(simulated_F < critical_F) break
}
# report the ANOVA
summary(aov.out)
# show a graph
library(ggplot2)
ggplot(random_data, aes(x=IV, y=DV))+
  geom_bar(stat="summary", fun="mean")+
  geom_point()
```
2)
```{r}

library(tibble)
levels <- 3
n_per_level <- 10
critical_F <- qf(.95,2,27)
# repeat until we find the data that meets the criterion
for(i in 1:1000){
  random_data <- tibble(subjects = 1:(levels*n_per_level),
                        IV = as.factor(rep(1:levels, each = n_per_level)),
                        DV = rnorm(levels*n_per_level, 0, 1)
                        )
  aov.out <- aov(DV ~ IV, data = random_data)
  simulated_F <- summary(aov.out)[[1]]$`F value`[1]
  
  if(simulated_F > critical_F) break
}
simulated_F > critical_F
# report the ANOVA
summary(aov.out)
# show a graph
library(ggplot2)
ggplot(random_data, aes(x=IV, y=DV))+
  geom_bar(stat="summary", fun="mean")+
  geom_point()

```