---
title: "lab7.rmd"
author: "Shawn Vizgan"
date: "5/12/2021"
output: html_document
---
1. (in progress)
3. 

```{r}
p1<- data.frame(IV1 = c("A","A","B","B"),
                IV2 = c("1","2","1","2"),
                means = c(6,6,6,6))
p2<- data.frame(IV1 = c("A","A","B","B"),
                IV2 = c("1","2","1","2"),
                means = c(10,10,5,5))
p3<- data.frame(IV1 = c("A","A","B","B"),
                IV2 = c("1","2","1","2"),
                means = c(10,13,5,2))
p4<- data.frame(IV1 = c("A","A","B","B"),
                IV2 = c("1","2","1","2"),
                means = c(5,10,10,15))
p5<- data.frame(IV1 = c("A","A","B","B"),
                IV2 = c("1","2","1","2"),
                means = c(10,18,5,7))
p6<- data.frame(IV1 = c("A","A","B","B"),
                IV2 = c("1","2","1","2"),
                means = c(10,2,10,2))
p7<- data.frame(IV1 = c("A","A","B","B"),
                IV2 = c("1","2","1","2"),
                means = c(2,12,5,9))
p8<- data.frame(IV1 = c("A","A","B","B"),
                IV2 = c("1","2","1","2"),
                means = c(5,10,10,5))
all_22s <- rbind(p1,p2,p3,p4,p5,p6,p7,p8)
type <- c(rep("~1, ~2, ~1x2",4),
          rep("1, ~2, ~1x2",4),
          rep("1, ~2, 1x2",4),
          rep("1, 2, ~1x2",4),
          rep("1, 2, 1x2",4),
          rep("~1, 2, ~1x2",4),
          rep("~1, 2, 1x2",4),
          rep("~1, ~2, 1x2",4))
type<-as.factor(type)
all_22s <- cbind(all_22s,type)
ggplot(all_22s, aes(x=IV1, y=means, group=IV2, fill=IV2))+
  geom_bar(stat="identity", position="dodge")+
  theme_classic()+
  facet_wrap(~type, nrow=2)+
  theme(legend.position = "top")
ggplot(all_22s, aes(x=IV1, y=means, group=IV2, color=IV2))+
  geom_point()+
  geom_line()+
  theme_classic()+
  facet_wrap(~type, nrow=2)+
  theme(legend.position = "top")
```

4) 

```{r}
sims <- rbinom(10000,7,.05)
length(sims[sims > 0])/10000
save_sim <- tibble()
# loop to conduct i number of simulations
for(i in 1:10000){
  #simulate null data for a 2x2
  n <- 12
  factorial_data <- tibble(A = factor(rep(c("L1","L2"), each = n)),
                         B = factor(rep(rep(c("L1","L2"), each = n/2),2)),
                         C = factor(rep(c("L1","L2"), n)),
                         DV = rnorm(n*2,0,1))
  # compute ANOVA
  output <- summary(aov(DV ~ A*B*C, data = factorial_data))
  #save p-values for each effect
  sim_tibble <- tibble(p_vals = output[[1]]$`Pr(>F)`[1:7],
                       effect = c("A","B","C","AxB","AxC","BxC","AxBxC"),
                       sim = rep(i,7))
  #add the saved values to the overall tibble
  save_sim <-rbind(save_sim,sim_tibble)
}
type_I_errors <- save_sim %>%
  filter(p_vals < .05) %>%
  group_by(sim) %>%
  count()
dim(type_I_errors)[1]/10000
```