---
title: "lab8.rmd"
author: "Shawn Vizgan"
date: "4/15/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

1)
A- 
```{r}
library(tibble)
library(ggplot2)
library(patchwork)
# define 2-factor score model
grand_mean <- 0
A <- c(0,.5)
B <- c(0,0)
AB <- c(0,0,0,-.25)
# create design table
model_data <- tibble()
for(i in 1:length(A)){
  for(j in 1:length(B)){
    IVA <- i 
    IVB <- j
    DV <- grand_mean+A[i]+B[j]+AB[(i-1)*length(B)+j]
    sc_GM <- grand_mean
    sc_A <- A[i]
    sc_B <- B[j]
    sc_AB <- AB[(i-1)*length(B)+j] 
    row_entry <- tibble(IVA,IVB,DV,
                        sc_GM,sc_A,sc_B,sc_AB)
    model_data <- rbind(model_data,row_entry)
  }
}
knitr::kable(model_data)
# generate plots
bar_graph <- ggplot(model_data, 
                    aes(y=DV,
                        x=as.factor(IVA),
                        fill=as.factor(IVB)))+
  geom_bar(stat='identity', position='dodge')
line_graph <- ggplot(model_data, 
                     aes(y=DV,
                         x=IVA,
                         linetype=as.factor(IVB)))+
  geom_line()+
  geom_point()
(bar_graph/line_graph)

```
B-
```{r}```{r}
# N per group
N <- 57
A_pvalue <- c()
B_pvalue <- c()
AB_pvalue <- c()
for(i in 1:1000){
  IVA <- rep(rep(c("1","2"), each=2),N)
  IVB <- rep(rep(c("1","2"), 2),N)
  DV <- c(replicate(N,c(rnorm(1,0,1), # means A1B1
                        rnorm(1,0,1), # means A1B2
                        rnorm(1,.5,1), # means A2B1
                        rnorm(1,.25,1)  # means A2B2
          )))
  sim_df <- data.frame(IVA,IVB,DV)
  
  aov_results <- summary(aov(DV~IVA*IVB, sim_df))
  A_pvalue[i]<-aov_results[[1]]$`Pr(>F)`[1]
  B_pvalue[i]<-aov_results[[1]]$`Pr(>F)`[2]
  AB_pvalue[i]<-aov_results[[1]]$`Pr(>F)`[3]
}
length(A_pvalue[A_pvalue<0.05])/1000
```

C- 
```{r}

N <- 500
AB_pvalue <- c()
for(i in 1:1000){
  
  sim_df <- tibble(
    IVA = rep(rep(c("1","2"), each=2),N),
    IVB = rep(rep(c("1","2"), 2),N),
    DV = rnorm(4*N,c(0,0,.5,.25),1)
  )
  aov_results <- summary(aov(DV~IVA*IVB, sim_df))
  AB_pvalue[i]<-aov_results[[1]]$`Pr(>F)`[3]
}
length(AB_pvalue[AB_pvalue<0.05])/1000
```










```
